/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTiffinboxRouteImport } from './routes/admin.tiffinbox'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminRoomBookingsRouteImport } from './routes/admin.room-bookings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRestaurantRouteImport } from './routes/admin.restaurant'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMarketingRoutesRouteImport } from './routes/admin.marketing-routes'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminEventsEditRouteImport } from './routes/admin.events.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiffinboxRoute = AdminTiffinboxRouteImport.update({
  id: '/tiffinbox',
  path: '/tiffinbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomBookingsRoute = AdminRoomBookingsRouteImport.update({
  id: '/room-bookings',
  path: '/room-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantRoute = AdminRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoutesRoute = AdminMarketingRoutesRouteImport.update({
  id: '/marketing-routes',
  path: '/marketing-routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEditRoute = AdminEventsEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contacts': typeof AdminContactsRoute
<<<<<<< HEAD
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
=======
  '/admin/events': typeof AdminEventsRouteWithChildren
>>>>>>> eventslink
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/marketing-routes': typeof AdminMarketingRoutesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/room-bookings': typeof AdminRoomBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiffinbox': typeof AdminTiffinboxRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/edit': typeof AdminEventsEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contacts': typeof AdminContactsRoute
<<<<<<< HEAD
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
=======
  '/admin/events': typeof AdminEventsRouteWithChildren
>>>>>>> eventslink
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/marketing-routes': typeof AdminMarketingRoutesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/room-bookings': typeof AdminRoomBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiffinbox': typeof AdminTiffinboxRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/edit': typeof AdminEventsEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contacts': typeof AdminContactsRoute
<<<<<<< HEAD
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
=======
  '/admin/events': typeof AdminEventsRouteWithChildren
>>>>>>> eventslink
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/marketing-routes': typeof AdminMarketingRoutesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/room-bookings': typeof AdminRoomBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tiffinbox': typeof AdminTiffinboxRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/edit': typeof AdminEventsEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/careers'
    | '/admin/contacts'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/marketing-routes'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reservations'
    | '/admin/restaurant'
    | '/admin/reviews'
    | '/admin/room-bookings'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/tiffinbox'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/admin/'
    | '/admin/events/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/careers'
    | '/admin/contacts'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/marketing-routes'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reservations'
    | '/admin/restaurant'
    | '/admin/reviews'
    | '/admin/room-bookings'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/tiffinbox'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/admin'
    | '/admin/events/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/about'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/careers'
    | '/admin/contacts'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/marketing-routes'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/reservations'
    | '/admin/restaurant'
    | '/admin/reviews'
    | '/admin/room-bookings'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/tiffinbox'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/admin/'
    | '/admin/events/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiffinbox': {
      id: '/admin/tiffinbox'
      path: '/tiffinbox'
      fullPath: '/admin/tiffinbox'
      preLoaderRoute: typeof AdminTiffinboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/room-bookings': {
      id: '/admin/room-bookings'
      path: '/room-bookings'
      fullPath: '/admin/room-bookings'
      preLoaderRoute: typeof AdminRoomBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurant': {
      id: '/admin/restaurant'
      path: '/restaurant'
      fullPath: '/admin/restaurant'
      preLoaderRoute: typeof AdminRestaurantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing-routes': {
      id: '/admin/marketing-routes'
      path: '/marketing-routes'
      fullPath: '/admin/marketing-routes'
      preLoaderRoute: typeof AdminMarketingRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/edit': {
      id: '/admin/events/edit'
      path: '/edit'
      fullPath: '/admin/events/edit'
      preLoaderRoute: typeof AdminEventsEditRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsEditRoute: typeof AdminEventsEditRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEditRoute: AdminEventsEditRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminContactsRoute: typeof AdminContactsRoute
<<<<<<< HEAD
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFaqRoute: typeof AdminFaqRoute
=======
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
>>>>>>> eventslink
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMarketingRoutesRoute: typeof AdminMarketingRoutesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminRestaurantRoute: typeof AdminRestaurantRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomBookingsRoute: typeof AdminRoomBookingsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTiffinboxRoute: typeof AdminTiffinboxRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminContactsRoute: AdminContactsRoute,
<<<<<<< HEAD
  AdminEventsRoute: AdminEventsRoute,
  AdminFaqRoute: AdminFaqRoute,
=======
  AdminEventsRoute: AdminEventsRouteWithChildren,
>>>>>>> eventslink
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMarketingRoutesRoute: AdminMarketingRoutesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminRestaurantRoute: AdminRestaurantRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomBookingsRoute: AdminRoomBookingsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTiffinboxRoute: AdminTiffinboxRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
